insert into Material (id,nombre,descripcion,cantidad) values (1, 'aceite','Aceite maroleo', 124)
insert into Material (id,nombre,descripcion,cantidad) values (2, 'azucar','Ledesma 500grs' , 80)
insert into Material (id,nombre,descripcion,cantidad) values (3, 'sal','Ledesma 500grs' , 4)
insert into Material (id,nombre,descripcion,cantidad) values (4, 'Cocacola 1.5L','' , 12)
insert into Material (id,nombre,descripcion,cantidad) values (5, 'Fideos','Luchetti 500grs' , 180)
insert into Material (id,nombre,descripcion,cantidad) values (6, 'yerba','' , 15)